local bg = {
	bg = {
		attribute = "bg",
		highlight = "Pmenu",
	},
}

return {
	"akinsho/bufferline.nvim",
	dependencies = { "nvim-tree/nvim-web-devicons" },
	opts = {
		options = {
			mode = "tabs", -- or "buffers"
			truncate_names = true, -- whether or not tab names should be truncated
			diagnostics = "nvim_lsp",
			diagnostics_update_in_insert = true,
			offsets = {
				{
					filetype = "NvimTree",
					text = "Files",
					text_align = "left",
					separator = true,
				},
			},
			tab_size = 22,
			max_name_length = 18,
			color_icons = true, -- whether or not to add the filetype icon highlights
			separator_style = "thin",
		},
		highlights = {
			-- fill = bg,
			background = bg,
			tab = bg,
			tab_selected = bg,
			tab_separator = bg,
			tab_separator_selected = bg,
			-- tab_close = bg,
			close_button = bg,
			close_button_visible = bg,
			close_button_selected = bg,
			buffer_visible = bg,
			buffer_selected = bg,
			-- numbers = bg,
			-- numbers_visible = bg,
			-- numbers_selected = bg,
			diagnostic = bg,
			diagnostic_visible = bg,
			diagnostic_selected = bg,
			hint = bg,
			hint_visible = bg,
			hint_selected = bg,
			hint_diagnostic_visible = bg,
			hint_diagnostic_selected = bg,
			info = bg,
			info_visible = bg,
			info_selected = bg,
			info_diagnostic = bg,
			info_diagnostic_visible = bg,
			info_diagnostic_selected = bg,
			warning = bg,
			warning_visible = bg,
			warning_selected = bg,
			warning_diagnostic = bg,
			warning_diagnostic_visible = bg,
			warning_diagnostic_selected = bg,
			error_visible = bg,
			error_selected = bg,
			error_diagnostic = bg,
			error_diagnostic_visible = bg,
			error_diagnostic_selected = bg,
			modified = bg,
			modified_visible = bg,
			modified_selected = bg,
			duplicate_selected = bg,
			duplicate_visible = bg,
			duplicate = bg,
			-- separator_selected = bg,
			-- separator_visible = bg,
			-- -- separator = bg,
			-- indicator_visible = bg,
			-- indicator_selected = bg,
			-- pick_selected = bg,
			-- pick_visible = bg,
			-- pick = bg,
			-- offset_separator = bg,
			-- trunc_marker = bg,
		},
	},
}
